export { default as Home } from './Home/Home'
export { default as About } from './About/About'
export { default as Search } from './Search/Search'
export { default as Tasks } from './Tasks/Tasks'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
